/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  EventEmitter,
} from '@stencil/core';

declare global {

  namespace StencilComponents {
    interface LazyImg {
      'alt': string;
      'src': string;
      'width': number;
    }
  }

  interface HTMLLazyImgElement extends StencilComponents.LazyImg, HTMLStencilElement {}

  var HTMLLazyImgElement: {
    prototype: HTMLLazyImgElement;
    new (): HTMLLazyImgElement;
  };
  interface HTMLElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  interface ElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'lazy-img': JSXElements.LazyImgAttributes;
    }
  }
  namespace JSXElements {
    export interface LazyImgAttributes extends HTMLAttributes {
      'alt'?: string;
      'onLazyImgloaded'?: (event: CustomEvent<HTMLImageElement>) => void;
      'src'?: string;
      'width'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface MadnessNfc {

    }
  }

  interface HTMLMadnessNfcElement extends StencilComponents.MadnessNfc, HTMLStencilElement {}

  var HTMLMadnessNfcElement: {
    prototype: HTMLMadnessNfcElement;
    new (): HTMLMadnessNfcElement;
  };
  interface HTMLElementTagNameMap {
    'madness-nfc': HTMLMadnessNfcElement;
  }
  interface ElementTagNameMap {
    'madness-nfc': HTMLMadnessNfcElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'madness-nfc': JSXElements.MadnessNfcAttributes;
    }
  }
  namespace JSXElements {
    export interface MadnessNfcAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
